pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                cleanWs()
                git branch: 'main', url: 'https://github.com/shusainov/pricer.git'
                dir('dataCollector'){
                    sh 'mvn package'
                    sh 'cp -r /home/shusainov/dataCollector/config config'
                }
            }
        }
        stage('image') {
            steps{
                script(){
                    dir('dataCollector'){
                        def VERSION = readMavenPom().getVersion()
                        echo "${VERSION}"
                        sh "docker build --no-cache --tag localhost:dataCollector --build-arg VERSION=${VERSION} ."
                    }
                }
            }
        }
        stage('deploy') {
            steps{
                sh "docker rm --force dataCollector"
                script(){docker.image('localhost:dataCollector').run('--name dataCollector -p 8081:8081 --restart=always')}
                //sh "docker run --name dataCollector localhost:dataCollector"
                echo "deploying"
            }
        }
    }
}
